Dec 21 2021
Rahul4321Kumar/Enquiry-Management-System pull request #1
Opened 2021-12-21 15:02 UTC by Rahul4321Kumar

This PR contains the following:-
1. Added two app (i.e user_app, Enquiry)
2. Added models of user and Enquiry
3. used abstractbaseuser to create user_app model

2021-12-21 15:38 UTC, ksilawat-deqode requested changes
Still needs improvement!
It's already mentioned in the doc for the names of the apps -> `users` & `enquiries`
Still you're having `user_app` in place of `users` & `Enquiry` in place of `enquiries`

Django apps names always follows snakecase!

Please focus on naming conventions and Review comments as well.

It doesn't contain any `requirements.txt`, please add it

2021-12-21 15:38 UTC, ksilawat-deqode commented on .gitignore
> +db.sqlite3
No newline at the end

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/EMS/settings.py
> +]
Here apps can be separated like,
```suggestion
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #integrated apps
    'rest_framework',
    
    #own apps
    'Enquiry',
    'user_app',
]
```

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/Enquiry/admin.py
> +admin.site.register(Enquiry)
Here 2 lines break should be present and then only you should start your implementations
```suggestion
from django.contrib import admin
from .models import Enquiry


admin.site.register(Enquiry)
```

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/Enquiry/admin.py
> +from .models import Enquiry
Always use absolute imports and not relative imports
```suggestion
from enquiries.models import Enquiry
```

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/Enquiry/models.py
> +class Enquiry(models.Model):
```suggestion
from django.db import models
from django.conf import settings


class Enquiry(models.Model):
```

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/Enquiry/models.py
> +    active = models.BooleanField()
You should add a default value for this `active` field.

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/Enquiry/models.py
> +    updated_at = models.DateTimeField(auto_now_add=True)
`created_at` is for at what time instance is created
 `updated_at` is for at what time instance is updated(or we can last modify)
But with your implementation, both fields are doing the same. Please read about `auto_now` & `auto_now_add`

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/user_app/admin.py
> +admin.site.register(User)
```suggestion
from django.contrib import admin
from users.models import User


admin.site.register(User)
```

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/user_app/managers.py
> +from django.contrib.auth.base_user import BaseUserManager
No need to create an extra file for only model managers, model managers reside inside `models.py`

2021-12-21 15:38 UTC, ksilawat-deqode commented on EMS/user_app/models.py
> +        (u'F', u'Female'),
Any specific reason for not using normal strings here?

2021-12-22 06:17 UTC, ksilawat-deqode requested changes
- Remove unused apps `Enquiry` & `user_app`
- Rename `EMS` folder to `ems` 
- Unapply all the migrations, delete them & recreate all migrations again(Only one migration should be there for each model as the definition of the models is cleared).

2021-12-22 06:17 UTC, ksilawat-deqode commented on EMS/enquiries/admin.py
> +admin.site.register(Enquiry)
No new line at the end

2021-12-22 06:17 UTC, ksilawat-deqode commented on EMS/enquiries/models.py
> +    resolved = models.BooleanField()
Add `default=False`.

2021-12-22 06:17 UTC, ksilawat-deqode commented on EMS/users/admin.py
> +admin.site.register(User)
No newline at the end

2021-12-22 06:17 UTC, ksilawat-deqode commented on EMS/users/models.py
> +class UserManager(BaseUserManager):
Convert it to private member for this particular module.

2021-12-22 06:17 UTC, ksilawat-deqode commented on EMS/users/models.py
> +        return self.email
No newline at the end.

2021-12-22 10:26 UTC, ksilawat-deqode commented on EMS/user_app/models.py
> +        (u'F', u'Female'),
Any answer to this question?

2021-12-22 10:36 UTC, Rahul4321Kumar commented on EMS/user_app/models.py
> +        (u'F', u'Female'),
('M', 'Male'),
('F', 'Female'),
we also write like this 
first element of each tuple value is set to model and second element for human readable

2021-12-22 10:52 UTC, ksilawat-deqode requested changes
Please do reply on question asked!

2021-12-22 10:52 UTC, ksilawat-deqode commented on EMS/users/models.py
> +    is_superuser = models.BooleanField(_('superuser'))
Please add a `default=False` for this field.

2021-12-22 10:52 UTC, ksilawat-deqode commented on EMS/users/models.py
> +from django.utils.translation import gettext_lazy as _
Any reason for using this thing?

2021-12-22 10:52 UTC, ksilawat-deqode commented on EMS/users/models.py
> +        (u'F', u'Female'),
Still haven't got any reason, why you used this thing?

2021-12-22 11:07 UTC, Rahul4321Kumar commented on EMS/users/models.py
> +from django.utils.translation import gettext_lazy as _
gettext_lazy is used to translate the string for end user its not neccessary for now

2021-12-22 11:27 UTC, ksilawat-deqode commented on EMS/users/models.py
> +from django.utils.translation import gettext_lazy as _
If it's not necessary for now, then remove it.

2021-12-22 11:47 UTC, Rahul4321Kumar commented on EMS/users/models.py
> +        (u'F', u'Female'),
'choices' must be an iterable containing (actual value, human readable name) tuples.

2021-12-22 11:55 UTC, Rahul4321Kumar commented on EMS/users/models.py
> +        (u'F', u'Female'),
in django-admin gender will be displayed as drop down

2021-12-22 12:14 UTC, ksilawat-deqode requested changes

2021-12-22 12:14 UTC, ksilawat-deqode commented on EMS/users/models.py
> +    is_staff = models.BooleanField(default=True)
This field should have `default=False`.
Do read about `is_staff` & `is_superuser` fields on `User` model.

2021-12-22 12:28 UTC, Rahul4321Kumar commented on EMS/users/models.py
> +    is_staff = models.BooleanField(default=True)
is_staff+is_superuser+active=True means its a main user(superuser)
is_staff+active=True means its a admin user
active=True mean its a normal user

2021-12-22 12:42 UTC, ksilawat-deqode requested changes
Update ASAP, will merge it after the update.

2021-12-22 12:42 UTC, ksilawat-deqode commented on EMS/users/models.py
> +    created_at = models.DateTimeField(auto_now_add = True)
Typo here
```suggestion
    created_at = models.DateTimeField(auto_now_add=True)
```

2021-12-22 12:46 UTC, ksilawat-deqode commented on EMS/users/models.py
> +        (u'F', u'Female'),
No, it's not an answer to the question asked

2021-12-22 12:47 UTC, Rahul4321Kumar commented on EMS/users/models.py
> +    created_at = models.DateTimeField(auto_now_add = True)
Done

2021-12-22 12:48 UTC, kishansilawat approved these changes
After this much iterations.

2021-12-22 12:49 UTC, merged