Dec 23 2021
Rahul4321Kumar/Enquiry-Management-System pull request #3
Opened 2021-12-23 11:08 UTC by Rahul4321Kumar

2021-12-23 13:56 UTC, ksilawat-deqode requested changes
Change authentication method to use `JWT`

2021-12-23 13:56 UTC, ksilawat-deqode commented on EMS/ems/urls.py
> +    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls'))
Change it to, 
```suggestion
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', include('dj_rest_auth.registration.urls'))
```

2021-12-23 13:56 UTC, ksilawat-deqode commented on EMS/users/serializers.py
> +    )
Make use of this from `models.py`

2021-12-23 13:56 UTC, ksilawat-deqode commented on EMS/users/serializers.py
> +        print(self.cleaned_data)
Don't forget to remove debug logs.

2021-12-23 14:20 UTC, Rahul4321Kumar commented on EMS/ems/urls.py
> +    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls'))
done

2021-12-23 14:20 UTC, Rahul4321Kumar commented on EMS/users/serializers.py
> +    )
done

2021-12-23 14:20 UTC, Rahul4321Kumar commented on EMS/users/serializers.py
> +        print(self.cleaned_data)
done

2021-12-24 06:46 UTC, ksilawat-deqode requested changes

2021-12-24 06:46 UTC, ksilawat-deqode commented on EMS/users/models.py
> +    )
Any constant should be defined inside a separate `constants.py` or if it's just a file-level constant define it at the top after 1 line break from the `imports`

2021-12-24 06:55 UTC, ksilawat-deqode approved these changes

2021-12-24 06:55 UTC, merged